### ISSUE TITLE
[BUG] - Inconsistency during vector write

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#52] opened 2023-10-27 16:47 UTC
**Describe the bug**
Executing the attached experiment I get the following error:
`Exception 'ZIAPIServerException with status code: 32782 - Command failed internally. Extended information: Inconsistency during vector write: sum of numBlock
Elements doesn't match numTotalElements', retrying... `

**Code & Screenshots**
[L1Q-20231027_00701_NQubitsInterleavedRB_['cphase', 'double_cphase']-20231027_00001_None_20231027T164024Z-00000.zip](https://github.com/zhinst/laboneq/files/13191351/L1Q-20231027_00701_NQubitsInterleavedRB_.cphase.double_cphase.-20231027_00001_None_20231027T164024Z-00000.zip)

**Versions used:**
 - laboneq: 2.13.0
 - zhinst-core==23.6.46756
 - zhinst-toolkit==0.6.1
 - zhinst-utils==0.3.3

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by QuantumClemens** [comment] 2023-10-30 12:25
@GlaserN thanks for notifying us of this issue! 
This is a known issue in rare cases which is caused by the core API in the communication to the dataserver. This has been addressed in the new version of LabOne 23.10, which is about to be released in the coming days. LabOne Q will support LabOne 23.10. from our next release, scheduled for 09.11.23

**Comment by QuantumClemens** [comment] 2023-11-15 09:43
updating this ticket, the support for LabOne 23.10 was delayed by one release, now expected for LabOne Q 2.20. Sory for the delay.

**Comment by QuantumClemens** [comment] 2024-01-03 07:33
Closing this ticket, solved by. migration to LabOne 23.10. Please let us know if this reappears.

**Closed by QuantumClemens** 2024-01-03 07:33 UTC
Labels: fix commited, jira
