### ISSUE TITLE
[BUG] - SHFQA multiplexed readout : incommensurate integration weights.

### ISSUE THREAD

**Issue by MalaySingh** [zhinst/laboneq#2] opened 2022-10-10 12:02 UTC
**Describe the bug**
The weights queried from the SHFQA using a node query do not correspond one-to one with weights uploaded by the user (i.e. to the compiled experiment).
 
**To Reproduce**
1. Consider the experiment.json & setup.json, it is 2 qubit on-off experiment. The two measure & acquire tones are ~1 GHz apart, essentially -500 MHz and 500 MHz, from the LO at 6.5 GHz.
2. The compiled experiment reports the correct weights, but when queried from the device, strange clipping is shown. The FFT of the weights reports a frequency that differs from supplied (SW oscillator) frequency by >10 MHz.
Device nodes queried:
weights:
daq.get(f'/dev12159/qachannels/{port}/readout/integration/weights/0/wave', flat=True)[f'/dev12159/qachannels/{port}/readout/integration/weights/0/wave'][0]['vector']
daq.get(f'/dev12159/qachannels/{port}/readout/integration/weights/1/wave', flat=True)[f'/dev12159/qachannels/{port}/readout/integration/weights/1/wave'][0]['vector']
![image](https://user-images.githubusercontent.com/12223390/194861451-3e71b764-9984-43f1-881f-128643cb347e.png)

measurement pulse:
daq.get('/dev12159/qachannels/0/generator/waveforms/0/wave', flat=True)['/dev12159/qachannels/0/generator/waveforms/0/wave'][0]['vector']
daq.get('/dev12159/qachannels/0/generator/waveforms/1/wave', flat=True)['/dev12159/qachannels/0/generator/waveforms/1/wave'][0]['vector']

![image](https://user-images.githubusercontent.com/12223390/194861363-bf935889-d358-4512-a253-e1dbb1055c54.png)

4. The multiplexed readout thus performed, shows a significant degradation of fidelity, which we attribute to partially incorrect weights.

**Expected behavior**
The queried weights should be almost the same as the one uploaded. The degradation seen in readout fidelity should be smaller.

**Versions used:**
Version laboneq 1.0.2, Labone 22.08, zhinst : 21.2.15439

**Context**
[experiment_setup_zipped.zip](https://github.com/zhinst/laboneq/files/9745924/experiment_setup_zipped.zip)

- [ ] No workaround known. Degrades readout fidelity.
- [ ] Yes, however the first demonstration of multiplexed readout was successful.

**Comment by zi-2k** [comment] 2022-10-10 19:32
This issue is related to #1, especially step 2 from the description has the same root cause:
> The compiled experiment reports the correct weights, but when queried from the device, strange clipping is shown.

It is not clear yet, if the read-out fidelity degradation is also caused by this. In case the root issue only affects the node readout, then the degraded fidelity must have a different cause. Otherwise, if corrupted weights are seen by the integrators same as on the node readout, this would explain degraded fidelity too.

**Comment by kshirer** [comment] 2022-10-11 12:47
Hi, the bug is due to a current issue in LabOne 22.08 which is being addressed in the upcoming patch release. As Konstantin stated, it is not yet clear if the fidelity issue is related, though it is likely an due to LabOne and not LabOne Q. We will be able to test this one our side shortly after internal testing of the 22.08 patch. At the moment, the readout weight uploaded to the device is correct, however, `daq.get` doesn't retrieve it correctly, resulting in your reported behavior. We should have an update to this issue shortly.

**Comment by zi-2k** [comment] 2022-10-11 12:48
It is already known, that only the weight node read out from the device was affected, not the actual data used for integration. This means degraded fidelity must have a different source.

**Comment by QuantumClemens** [comment] 2022-11-07 08:10
This issue should be fixed with the new LabOne firmware, which LabOne Q will now depend on. When installing LabOne Q, make sure to also update the firmware on your instruments through the LabOne GUI. 
Closing this issue.

**Closed by QuantumClemens** 2022-11-07 08:10 UTC
