### ISSUE TITLE
[Feature] - Multiple qubit measure lines in UHFQA in spectroscopy mode

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#10] opened 2022-11-04 10:27 UTC
**Describe the bug**
with experiment using UHFQA, and spectroscopy mode, get compilation error : `Attempting to multiplex several HW-modulated signals (measure_0, measure_1) on uhfqa, which does not support oscillator switching`.

in the experiment, there are 2 qubits sharing the same physical measure line, but in `SignalCalibration` only one is assigned an `Oscillator` with `ModulationType.HARDWARE`, the other is assigned an` Oscillator` with `ModulationType.SOFTWARE`.

The error raised from` laboneq/compiler/code_generator/analyze_events.py", line 418, in analyze_oscillator_switch_events`
and the reason is that in `line405`, `hw_oscillators` contains both signals even one of them has `signals[signal_id].hw_oscillator=None`, and the code thinks there are two different hardware oscillators.

**To Reproduce**
1. Define pulse sequence...
2. Execute on hardware / in emulation ...
3. Do additional steps...
[example.zip](https://github.com/zhinst/laboneq/files/9937293/example.zip)

**Expected behavior**
do not add the signal to the dictionary if the hardware oscillator is None

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq 1.2

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by QuantumClemens** [comment] 2022-11-07 08:08
Hi @YuanG13 - thanks for reporting this. 
This may be intended behavior, since in spectroscopy mode, multiplexing of measurement signals is not possible - i.e. the issue here is that in spectroscopy mode it is not possible to use multiple measurement signals. 
What exactly are your trying to do with this experiment?

**Comment by YuanG13** [comment] 2022-11-07 08:35
Yes, but only one qubit is intended and meant to be measured in that experiment. Since we are using qiskit circuits, if a nexperiment contains coupler but only one qubit is measured, which has longer measure pulse time (>2.3us, for example fluxonium), the circuit should contains 2 qubits and the meas_level is spectroscopy.

However regardless the experiment, counting Nonetype as an additional hardware oscillator seems too strict.

**Comment by QuantumClemens** [comment] 2022-11-07 08:50
I agree that we should probably improve the error message in this case, but as I understand the issue, this appears because there are two measurment lines in the experiment? 
From the files you provided that is the case, there are `measure_0` and `measure_1` as well as `acquire_0` and `acquire_1` - what happens when you remove those additional, unused lines from the experiment?

**Comment by YuanG13** [comment] 2022-11-07 13:35
Yes there are two lines, but only one Hardware oscillator is assigned, the other one is not assigned with any Hardware oscillator(None), as I described in the description. It should not be counted as multiplexing since only one frequency is involved.

**Comment by QuantumClemens** [comment] 2022-11-07 15:16
@YuanG13 using one line with hardware and another one with software oscillator is not possible in spectroscopy mode, you can only use a single readout line with hardware modulation in this mode. 
As mentioned earlier, the error message in this case is likely misleading. But it seems what you are trying to do might not be possible on the hardware.

**Comment by QuantumClemens** [comment] 2022-11-07 16:24
Yes, that is possible, if you do not assign an oscillator in the SignalCalibration, it will default to None. 
Can you clarify for me again, what you are attempting to do on the second measure line, the one with the software modulation?

**Comment by YuanG13** [comment] 2022-11-07 16:39
Nothing will do on that measure_1 and acquire_1. But the drive_1, flux_1 might have pulses.

So we either assign a None oscillator to the SignalCalibration of measure_1, acquire_1, or do not define SignalCalibration for measure_1, acquire_1 while still keep drive_1, flux_1 the same. Which one should be more reasonable from your perspective?

**Comment by QuantumClemens** [comment] 2022-11-08 07:10
I would suggest to remove the measure_1 and acquire_1 signal lines from the experiment. Then it should work already now, but as long as the lines are defined, their properties will be checked for conflicts with possible behavior. In this case one conflict will be that measurement multiplexing is not possible in spectroscopy mode.

**Comment by QuantumClemens** [comment] 2022-12-14 09:17
@YuanG13 - I will change this into a feature, since we will be adding functionality here, and I believe there is a simple workaround for the moment. This is planned as part of the integration of qubit objects as high level experiment objects, which is currently being planned

**Comment by QianmuZI** [comment] 2024-02-26 07:52
Hi @YuanG13, as discussed, we close this ticket.

**Closed** 2024-02-26 08:03 UTC
Labels: enhancement, jira
